version: '3.7'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./rocketdata
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./rocketdata/:/usr/src/rocketdata/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev

  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.7-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=rocketdatauser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rocketdatadb

volumes:
  postgres_volume: